
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
//import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Image from "next/image";
import { GroupProvider } from "./context/GroupContext";
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import AuthProvider from "@/utils/providers/AuthProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();


  return (
    <AuthProvider>
      <ReactQueryClientProvider>

        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <GroupProvider>
              <div className=" ">
                <nav className="h-[4rem] flex ">
                  <Navbar />
                </nav>
                <main className="h-[calc(100vh-4rem)] w-full">{children}</main>
              </div>
            </GroupProvider>
          </body>
        </html>
      </ReactQueryClientProvider>
    </AuthProvider>
  );
}
